server:
  port: 8081
  host: "0.0.0.0"
  read_timeout: "15s"
  write_timeout: "15s"

auth:
  user_id_header: "X-User-ID"
  email_header: "X-User-Email"
  handler_header: "X-User-Handler"

cors:
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
  allowed_headers: ["Content-Type", "Authorization", "X-User-ID", "X-User-Email", "X-User-Handler"]

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres" 
  database: "messaging_app"
  ssl_mode: "disable"
  max_connections: 25
  max_idle_time: "15m"
  conn_max_lifetime: "1h"

nats:
  url: "nats://localhost:4222"
  max_reconnects: 10
  reconnect_wait: "2s"
  connect_timeout: "5s"
  request_timeout: "10s"
  enable_jetstream: false
  cluster_name: ""

logging:
  level: "info"

environment: "production"