version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: messaging-app-postgres-test
    environment:
      POSTGRES_DB: messaging_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d messaging_app"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  nats:
    image: nats:2.10-alpine
    container_name: messaging-app-nats-test
    environment:
      - NATS_SERVER_NAME=nats-standalone
    ports:
      - "4222:4222" # NATS client connections
      - "8222:8222" # NATS monitoring
      - "8080:8080" # WebSocket connections
    volumes:
      - ./e2e/nats.conf:/etc/nats/nats.conf:ro
    command: ["-c", "/etc/nats/nats.conf"]
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8222/varz",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  postgres_test_data:
  nats_test_data:
