name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Start services with docker compose
      run: docker compose up -d

    - name: Wait for services to be ready
      run: |
        # Wait for PostgreSQL
        until docker compose exec -T postgres pg_isready -U postgres -d messaging_app; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

        # Wait for NATS
        until curl -f http://localhost:8222/varz; do
          echo "Waiting for NATS..."
          sleep 2
        done

        echo "Services are ready!"

    - name: Run all tests
      run: go test -v ./...
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: messaging_app
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        NATS_URL: nats://localhost:4222

    - name: Stop services
      run: docker compose down
      if: always()